---
#- name: configure and deploy the webservers and apps
#  hosts: webservers
#  remote_user: root
 # roles:
  #  - web

- name: deploy and configure the databases
#  hosts: dbservers
  hosts: localhost
  remote_user: root
  vars_files:
    - [ "vars/RedHat.yml", "vars/Debian.yml" ]
  roles:
    - web
    - database

#- name: configure and deploy the drupal
#  hosts: localhost
#  remote_user: root
 # roles:
    - drupal
