---
# tasks file for database
- name: install database {{ packager_db }} package
#  package:
#   name: "{{ packager_db }}"
  package:
   name: "{{ item }}"
   state: present

  with_items:
   - "{{ packager_db }}"
   - MySQL-python

- name: Start {{ packager_db  }} Service
  service:
   name: '{{ packager_service }}'
   state: started
   enabled: yes

- name: Create a database user
  mysql_user:
   name: "{{ _db_user }}"
   password: "{{ _db_password }}"
   priv: "{{ _db_name }}.*:ALL"
   host: "{{ _host }}"
   state: present

- name: Create a new database for drupal
  mysql_db: 
   name: "{{ _db_name }}"
   login_password: "{{ _db_password }}"
   collation: "{{ _db_collation }}" 
   encoding: "{{ _db_encoding }}"
   login_user: "{{ _db_user }}"
   state: present
