---
# tasks file for roles/web {{ ansible_distribution }}

# - name: loading variables mention on file {{ ansible_distribution }}.yml
  # include_vars: "{{ item }}"
  # with_first_found:
   # - RedHat.yml
    #- Debian.yml

 - name: install {{ packager_web }} webservers package
   package: 
    name: "{{ item }}"
    state: present
   with_items:
    - "{{ packager_web }}"

 - name: enable webservers
   service:
    name: "{{ packager_web }}"
    state: started
    enabled: yes

# - name: configure {{ packager_web }} config file
#   template: 
#    src: "{{ _web_src_file }}"
#    dest: "{{ _config_dest_path }}"
#   command: nano /etc/ansible/ansible-drupal/roles/web/templates/'{{ template_web }}' >> {{ config_path_web }}

 - name: restart {{ packager_web }} service
   service:
    name: "{{ packager_web }}"
    state: restarted
