---
# tasks file for roles/drupal

- name: Download Drupal {{ _drupal_version }}
  get_url: 
   url: https://ftp.drupal.org/files/projects/drupal-{{ _drupal_version }}.tar.gz
   dest: /var/www/drupal-{{ _drupal_version }}.tar.gz
   mode: 0744

- name: extract archive {{ _drupal_path }}
#  shell:
#   chdir: /var/www/ /bin/tar xvf drupal-{{ _drupal_version }}.tar.gz 
#   creates: "{{ _drupal_path }}/drupal"
  unarchive:
   src: /var/www/drupal-{{ _drupal_version }}.tar.gz
   dest: /var/www/html/
   list_files: yes
   mode: 0755

- name: change unarchiving filename
  command: mv /var/www/html/drupal-{{ _drupal_version }} /var/www/html/drupal

- name: Give permission for files directory
  file:
    dest: "{{ _drupal_path }}/drupal"
    recurse: yes
    mode: 0777
- name: Add group drupal
  group: 
   name: "{{ _drupal_group }}"

- name: Create drupal user
  user:
   name: "{{ _drupal_user }}"
   password: "{{ _drupal_password | password_hash('sha512') }}"
   home: "/var/www/html/drupal/"
   group: "{{ _drupal_group }}"
   shell: "/bin/bash"


- name: Drupal | Drush site install if not already installed
  command: >
    drush site-install -y
    --site-name="{{ _drupal_site_name }}"
    --account-name={{ _drupal_user }}
    --account-pass={{ _drupal_password }}
    --db-url=mysql://{{ _db_user }}:{{ _db_password }}@{{ _host }}/{{ _db_name }}
    -r {{ _drupal_path }}/drupal
  state: restarted
